"""empty message

Revision ID: 64258b2fc72e
Revises: b339184edc62
Create Date: 2021-09-30 15:43:28.888607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64258b2fc72e'
down_revision = 'b339184edc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('item_name_uix', 'item', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_name_uix', 'item', type_='unique')
    # ### end Alembic commands ###
